### ISSUE TITLE
regression bug - module 'pyodide' has no attribute 'http'

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#97]
I am not sure whats going on here.. this below code worked two times  after I upgraded to 0.3.18 and broken since the third run. I have http server serving static files. between the first run and the second run, only thing I did was to change values in the the Year column of the CSV file to see how fast the app was picking up changes and rendering the df on refresh. As I said above, it worked second time as well showing the changes and since then not working, i restarted the pysheets server, static server and it doesn't work.  The static server log is 200 for the request. 

```
=
import pandas

url = "http://127.0.0.1:5000/adult-depression-lghc-indicator-24.csv"
csv = pyodide.http.open_url(url)
df = pandas.read_csv(csv)
adult_deppression_indicator = df[ ["Year", "Frequency", "Strata Name", "Percent"] ]

```
@laffra @sangramsingh-kss

**Comment by laffra** [comment]
I am not sure what is happening there either. I loaded the same CSV by using the `Import` button:

![Screenshot 2024-10-11 102952](https://github.com/user-attachments/assets/98db8c29-ac42-4e15-8657-d2d835095ffa)

**Comment by laffra** [comment]
I see the dataframe when I use `Load as Dataframe`:

![image](https://github.com/user-attachments/assets/8fcef540-c4e5-418b-87bf-c2fd4b0a6724)

I also see it in the sheet, when I select `Import into Sheet` and then click the `⭐A1` button:

![Screenshot 2024-10-11 103613](https://github.com/user-attachments/assets/ba9017bf-6f08-44da-b13d-abbd19893cb9)

**Comment by laffra** [comment]
In the worker, when importing "pyodide", it has code+ffi+webloop, but not http. I am not sure why...

![Screenshot 2024-10-13 132042](https://github.com/user-attachments/assets/aee8a801-6b49-476c-bbfa-0bf5e9e7ef3b)
